### ISSUE TITLE
Cant start frontend

### ISSUE THREAD

**Issue by aw-creative** [wesbos/javascript-drones#11]
TypeError: Cannot read property 'current' of undefined
    at Object.<anonymous> (C:\mplayer\javascript-drones\frontend\node_modules\react-ssr-prepass\dist\react-ssr-prepass.development.js:842:45)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\mplayer\javascript-drones\frontend\node_modules\react-ssr-prepass\index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactapp@1.0.0 dev: `next -p 7777`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactapp@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by gearsmotion789** [comment]
@aw-creative React and React DOM must be at least 16.8.0 in order to work. So go into frontend/package.json & change the following lines to the below. It should work.

"react": "16.8.0-alpha.0 - next",
"react-dom": "16.8.0-alpha.0 - next",

**Comment by ianlcz** [comment]
I can't use your frontend interface. I install dependences `npm install` and I run frontend's code `npm start` or `npm run dev`, this following message display in my terminal: 

```
Expected Document Component Html was not rendered. Make sure you render them in your custom `_document`
See more info here https://err.sh/next.js/missing-document-component
```

Also I was connected my macBook on the Tello Drone WiFi connection.

**Have you an idea to resolve this problem ?**
